export enum CardID {
  // Spades
  ACE_SPADES = "AS",
  TWO_SPADES = "2S",
  THREE_SPADES = "3S",
  FOUR_SPADES = "4S",
  FIVE_SPADES = "5S",
  SIX_SPADES = "6S",
  SEVEN_SPADES = "7S",
  EIGHT_SPADES = "8S",
  NINE_SPADES = "9S",
  TEN_SPADES = "10S",
  JACK_SPADES = "JS",
  QUEEN_SPADES = "QS",
  KING_SPADES = "KS",

  // Hearts
  ACE_HEARTS = "AH",
  TWO_HEARTS = "2H",
  THREE_HEARTS = "3H",
  FOUR_HEARTS = "4H",
  FIVE_HEARTS = "5H",
  SIX_HEARTS = "6H",
  SEVEN_HEARTS = "7H",
  EIGHT_HEARTS = "8H",
  NINE_HEARTS = "9H",
  TEN_HEARTS = "10H",
  JACK_HEARTS = "JH",
  QUEEN_HEARTS = "QH",
  KING_HEARTS = "KH",

  // Diamonds
  ACE_DIAMONDS = "AD",
  TWO_DIAMONDS = "2D",
  THREE_DIAMONDS = "3D",
  FOUR_DIAMONDS = "4D",
  FIVE_DIAMONDS = "5D",
  SIX_DIAMONDS = "6D",
  SEVEN_DIAMONDS = "7D",
  EIGHT_DIAMONDS = "8D",
  NINE_DIAMONDS = "9D",
  TEN_DIAMONDS = "10D",
  JACK_DIAMONDS = "JD",
  QUEEN_DIAMONDS = "QD",
  KING_DIAMONDS = "KD",

  // Clubs
  ACE_CLUBS = "AC",
  TWO_CLUBS = "2C",
  THREE_CLUBS = "3C",
  FOUR_CLUBS = "4C",
  FIVE_CLUBS = "5C",
  SIX_CLUBS = "6C",
  SEVEN_CLUBS = "7C",
  EIGHT_CLUBS = "8C",
  NINE_CLUBS = "9C",
  TEN_CLUBS = "10C",
  JACK_CLUBS = "JC",
  QUEEN_CLUBS = "QC",
  KING_CLUBS = "KC"
}

export const CARD_SVG_BASE_PATH = 'assets/images/card_icons/';

export const CARD_SVGS: Record<CardID, string> = {
  // Spades
  [CardID.ACE_SPADES]: `${CARD_SVG_BASE_PATH}ace_of_spades.svg`,
  [CardID.TWO_SPADES]: `${CARD_SVG_BASE_PATH}2_of_spades.svg`,
  [CardID.THREE_SPADES]: `${CARD_SVG_BASE_PATH}3_of_spades.svg`,
  [CardID.FOUR_SPADES]: `${CARD_SVG_BASE_PATH}4_of_spades.svg`,
  [CardID.FIVE_SPADES]: `${CARD_SVG_BASE_PATH}5_of_spades.svg`,
  [CardID.SIX_SPADES]: `${CARD_SVG_BASE_PATH}6_of_spades.svg`,
  [CardID.SEVEN_SPADES]: `${CARD_SVG_BASE_PATH}7_of_spades.svg`,
  [CardID.EIGHT_SPADES]: `${CARD_SVG_BASE_PATH}8_of_spades.svg`,
  [CardID.NINE_SPADES]: `${CARD_SVG_BASE_PATH}9_of_spades.svg`,
  [CardID.TEN_SPADES]: `${CARD_SVG_BASE_PATH}10_of_spades.svg`,
  [CardID.JACK_SPADES]: `${CARD_SVG_BASE_PATH}jack_of_spades.svg`,
  [CardID.QUEEN_SPADES]: `${CARD_SVG_BASE_PATH}queen_of_spades.svg`,
  [CardID.KING_SPADES]: `${CARD_SVG_BASE_PATH}king_of_spades.svg`,

  // Hearts
  [CardID.ACE_HEARTS]: `${CARD_SVG_BASE_PATH}ace_of_hearts.svg`,
  [CardID.TWO_HEARTS]: `${CARD_SVG_BASE_PATH}2_of_hearts.svg`,
  [CardID.THREE_HEARTS]: `${CARD_SVG_BASE_PATH}3_of_hearts.svg`,
  [CardID.FOUR_HEARTS]: `${CARD_SVG_BASE_PATH}4_of_hearts.svg`,
  [CardID.FIVE_HEARTS]: `${CARD_SVG_BASE_PATH}5_of_hearts.svg`,
  [CardID.SIX_HEARTS]: `${CARD_SVG_BASE_PATH}6_of_hearts.svg`,
  [CardID.SEVEN_HEARTS]: `${CARD_SVG_BASE_PATH}7_of_hearts.svg`,
  [CardID.EIGHT_HEARTS]: `${CARD_SVG_BASE_PATH}8_of_hearts.svg`,
  [CardID.NINE_HEARTS]: `${CARD_SVG_BASE_PATH}9_of_hearts.svg`,
  [CardID.TEN_HEARTS]: `${CARD_SVG_BASE_PATH}10_of_hearts.svg`,
  [CardID.JACK_HEARTS]: `${CARD_SVG_BASE_PATH}jack_of_hearts.svg`,
  [CardID.QUEEN_HEARTS]: `${CARD_SVG_BASE_PATH}queen_of_hearts.svg`,
  [CardID.KING_HEARTS]: `${CARD_SVG_BASE_PATH}king_of_hearts.svg`,

  // Diamonds
  [CardID.ACE_DIAMONDS]: `${CARD_SVG_BASE_PATH}ace_of_diamonds.svg`,
  [CardID.TWO_DIAMONDS]: `${CARD_SVG_BASE_PATH}2_of_diamonds.svg`,
  [CardID.THREE_DIAMONDS]: `${CARD_SVG_BASE_PATH}3_of_diamonds.svg`,
  [CardID.FOUR_DIAMONDS]: `${CARD_SVG_BASE_PATH}4_of_diamonds.svg`,
  [CardID.FIVE_DIAMONDS]: `${CARD_SVG_BASE_PATH}5_of_diamonds.svg`,
  [CardID.SIX_DIAMONDS]: `${CARD_SVG_BASE_PATH}6_of_diamonds.svg`,
  [CardID.SEVEN_DIAMONDS]: `${CARD_SVG_BASE_PATH}7_of_diamonds.svg`,
  [CardID.EIGHT_DIAMONDS]: `${CARD_SVG_BASE_PATH}8_of_diamonds.svg`,
  [CardID.NINE_DIAMONDS]: `${CARD_SVG_BASE_PATH}9_of_diamonds.svg`,
  [CardID.TEN_DIAMONDS]: `${CARD_SVG_BASE_PATH}10_of_diamonds.svg`,
  [CardID.JACK_DIAMONDS]: `${CARD_SVG_BASE_PATH}jack_of_diamonds.svg`,
  [CardID.QUEEN_DIAMONDS]: `${CARD_SVG_BASE_PATH}queen_of_diamonds.svg`,
  [CardID.KING_DIAMONDS]: `${CARD_SVG_BASE_PATH}king_of_diamonds.svg`,

  // Clubs
  [CardID.ACE_CLUBS]: `${CARD_SVG_BASE_PATH}ace_of_clubs.svg`,
  [CardID.TWO_CLUBS]: `${CARD_SVG_BASE_PATH}2_of_clubs.svg`,
  [CardID.THREE_CLUBS]: `${CARD_SVG_BASE_PATH}3_of_clubs.svg`,
  [CardID.FOUR_CLUBS]: `${CARD_SVG_BASE_PATH}4_of_clubs.svg`,
  [CardID.FIVE_CLUBS]: `${CARD_SVG_BASE_PATH}5_of_clubs.svg`,
  [CardID.SIX_CLUBS]: `${CARD_SVG_BASE_PATH}6_of_clubs.svg`,
  [CardID.SEVEN_CLUBS]: `${CARD_SVG_BASE_PATH}7_of_clubs.svg`,
  [CardID.EIGHT_CLUBS]: `${CARD_SVG_BASE_PATH}8_of_clubs.svg`,
  [CardID.NINE_CLUBS]: `${CARD_SVG_BASE_PATH}9_of_clubs.svg`,
  [CardID.TEN_CLUBS]: `${CARD_SVG_BASE_PATH}10_of_clubs.svg`,
  [CardID.JACK_CLUBS]: `${CARD_SVG_BASE_PATH}jack_of_clubs.svg`,
  [CardID.QUEEN_CLUBS]: `${CARD_SVG_BASE_PATH}queen_of_clubs.svg`,
  [CardID.KING_CLUBS]: `${CARD_SVG_BASE_PATH}king_of_clubs.svg`,
};